### ISSUE TITLE
Possible to also make cursewords compatible with Windows?

### ISSUE THREAD

**Issue by timtebbe** [thisisparker/cursewords#22]
I originally got "ImportError: No module named '_curses'", so installed Curses from https://www.lfd.uci.edu/~gohlke/pythonlibs/#curses, but now I get a UserWarning out of blessed.terminal, and nothing happens.

c:\program files\python35\lib\site-packages\blessed\terminal.py:32: UserWarning: One or more of the modules: 'termios', 'fcntl', and 'tty' are not found on your platform 'win32'. The following methods of Terminal are dummy/no-op unless a deriving class overrides them: setraw, cbreak, kbhit, height, width warnings.warn(_MSG_NOSUPPORT)
This puzzle is 15 columns wide and 15 rows tall. The terminal window must be taller to properly display  it.

**Comment by thisisparker** [comment]
`cursewords` probably won't be natively Windows compatible for a long time, because the `curses` wrapper it relies on—`blessed`—isn't. There's some suggestion that it could one day be, and if I could easily get Windows support by upgrading there, I'd of course be happy to do so.

BUT! I've heard from folks that if you use Windows Subsystem for Linux (in Windows 10), it "just works." I am not a Windows user and don't have access to a Windows machine, so unfortunately I couldn't give you more specific directions than that.

**Comment by chungy** [comment]
Might also be possible to use Cygwin to support running it, if you have Windows 10 Home or older versions of Windows.

**Comment by jquast** [comment]
The `blessed` library has been compatible with windows since Dec. 2019, have another look by upgrading, `pip install -U blessed`

**Comment by culcube** [comment]
> BUT! I've heard from folks that if you use Windows Subsystem for Linux (in Windows 10), it "just works." I am not a Windows user and don't have access to a Windows machine, so unfortunately I couldn't give you more specific directions than that.

Interestingly I've hit a bug using WSL2, and I don't know if you would rather it get filed here or a new issue filed.

**Comment by thisisparker** [comment]
Should now work just fine as of v1.0.8!
